title: M.K. Carroll
author: mkc808
email: mkcarroll@icloud.com
description: > # this means to ignore newlines until "baseurl:"
  Resume for M.K. Carroll

# social links
github_username:  mkc808 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
